//
//  MovieDetailModuleFormatter.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/9/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailModuleFormatter {
}

// MARK: - Extensions -

extension MovieDetailModuleFormatter: MovieDetailModuleFormatterInterface {
}
