//
//  MovieDetailModuleInterfaces.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/9/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailsNavigationOption {
    case back
}

protocol MovieDetailModuleWireframeInterface: WireframeInterface {
    func navigate(to option: DetailsNavigationOption)
}

protocol MovieDetailModuleViewInterface: ViewInterface {
}

protocol MovieDetailModulePresenterInterface: PresenterInterface {
    func closeMovieDetailView()
}

protocol MovieDetailModuleFormatterInterface: FormatterInterface {
}

protocol MovieDetailModuleInteractorInterface: InteractorInterface {
}
