//
//  MovieDetailModulePresenter.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/9/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailModulePresenter {

    // MARK: - Private properties -

    private unowned let view: MovieDetailModuleViewInterface
    private let formatter: MovieDetailModuleFormatterInterface
    private let interactor: MovieDetailModuleInteractorInterface
    private let wireframe: MovieDetailModuleWireframeInterface

    // MARK: - Lifecycle -

    init(view: MovieDetailModuleViewInterface, formatter: MovieDetailModuleFormatterInterface, interactor: MovieDetailModuleInteractorInterface, wireframe: MovieDetailModuleWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MovieDetailModulePresenter: MovieDetailModulePresenterInterface {
    func closeMovieDetailView() {
        wireframe.navigate(to: .back)
    }
}
