//
//  OnlineSearchModuleInterfaces.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/10/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol OnlineSearchModuleWireframeInterface: WireframeInterface {
}

protocol OnlineSearchModuleViewInterface: ViewInterface {
    func startLoading()
    func finishLoading()
    func setMoviesList(movieArray:[Movie])
    func showErrorView()
    func showEmptyView()
}

protocol OnlineSearchModulePresenterInterface: PresenterInterface {
    func searchByTitle(term: String)
}

protocol OnlineSearchModuleInteractorInterface: InteractorInterface {
    func searchByTitle(term: String, completion: @escaping MoviesServiceResult)
}
