//
//  OnlineSearchModuleInteractor.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/10/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class OnlineSearchModuleInteractor {
    let movieService = AlamofireMovieService(context: NonPersistentApiContext(environment: ApiEnvironment.production))
}

// MARK: - Extensions -

extension OnlineSearchModuleInteractor: OnlineSearchModuleInteractorInterface {
    func searchByTitle(term: String, completion: @escaping MoviesServiceResult) {
        movieService.searchMovieBy(title: term) { (_, apiMoviesResponse, responseError) in
            completion(apiMoviesResponse, responseError)
        }
    }
}
