//
//  OnlineSearchModuleWireframe.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/10/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class OnlineSearchModuleWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: OnlineSearchModuleViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = OnlineSearchModuleInteractor()
        let presenter = OnlineSearchModulePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

    init(viewControllerInstance: UIViewController) {
        let moduleViewController:OnlineSearchModuleViewController = viewControllerInstance as! OnlineSearchModuleViewController

        super.init(viewController: moduleViewController)

        let interactor = OnlineSearchModuleInteractor()
        let presenter = OnlineSearchModulePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension OnlineSearchModuleWireframe: OnlineSearchModuleWireframeInterface {
}
