//
//  MovieCollectionModulePresenter.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/8/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieCollectionModulePresenter {

    // MARK: - Private properties -

    private unowned let view: MovieCollectionModuleViewInterface
    private let formatter: MovieCollectionModuleFormatterInterface
    private let interactor: MovieCollectionModuleInteractorInterface
    private let wireframe: MovieCollectionModuleWireframeInterface

    // MARK: - Lifecycle -

    init(view: MovieCollectionModuleViewInterface,
         formatter: MovieCollectionModuleFormatterInterface,
         interactor: MovieCollectionModuleInteractorInterface,
         wireframe: MovieCollectionModuleWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MovieCollectionModulePresenter: MovieCollectionModulePresenterInterface {
}
