//
//  MovieCollectionModuleInteractor.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/8/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

enum MovieCategoryType: Int {
    case topRated
    case popular
    case upcoming
    case none

}

final class MovieCollectionModuleInteractor {
    let movieService = AlamofireMovieService(context: NonPersistentApiContext(environment: ApiEnvironment.production))
}

// MARK: - Extensions -

extension MovieCollectionModuleInteractor: MovieCollectionModuleInteractorInterface {
    func getMovieList(for movieCategoryType: MovieCategoryType, completion: @escaping (ApiMovie?, Error?) -> Void) {
        switch movieCategoryType {
        case .topRated:
            movieService.getTopRatedMovies { (_, apiMoviesResponse, responseError) in
                completion(apiMoviesResponse, responseError)
            }
        case .popular:
            movieService.getPopularMovies { (_, apiMoviesResponse, responseError) in
                completion(apiMoviesResponse, responseError)
            }
        case .upcoming:
            movieService.getUpcomingMovies { (_, apiMoviesResponse, responseError) in
                completion(apiMoviesResponse, responseError)
            }
        case .none:
            break
        }
    }
}
