//
//  MovieCollectionModuleInterfaces.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/8/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationOption {
    case home
    case details(Int)
}

protocol MovieCollectionModuleWireframeInterface: WireframeInterface {
}

protocol MovieCollectionModuleViewInterface: ViewInterface {
}

protocol MovieCollectionModulePresenterInterface: PresenterInterface {
}

protocol MovieCollectionModuleFormatterInterface: FormatterInterface {
}

protocol MovieCollectionModuleInteractorInterface: InteractorInterface {
}
