//
//  MovieCollectionModuleWireframe.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/8/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieCollectionModuleWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: MovieCollectionModuleViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = MovieCollectionModuleFormatter()
        let interactor = MovieCollectionModuleInteractor()
        let presenter = MovieCollectionModulePresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

    init(viewControllerInstance: UIViewController) {

        let moduleViewController: MovieCollectionModuleViewController = viewControllerInstance as! MovieCollectionModuleViewController

        super.init(viewController: moduleViewController)

        let formatter = MovieCollectionModuleFormatter()
        let interactor = MovieCollectionModuleInteractor()
        let presenter = MovieCollectionModulePresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MovieCollectionModuleWireframe: MovieCollectionModuleWireframeInterface {

    func navigate(to option: HomeNavigationOption) {
        switch option {
        case .details(let movieId):
            _openDetails(with: movieId)
        default:
            break
        }
    }

    private func _openDetails(with movieId: Int) {

    }

}
