//
//  MovieCollectionModuleInteractor.swift
//  Movie DB Test
//
//  Created by John Edwin Guerrero Ayala on 6/8/19.
//  Copyright (c) 2019 John Edwin Guerrero Ayala. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

enum MovieCategoryType {
    case none
}

final class MovieCollectionModuleInteractor {
}

// MARK: - Extensions -

extension MovieCollectionModuleInteractor: MovieCollectionModuleInteractorInterface {
    func getMovieList(for movieCategoryType: MovieCategoryType) -> [Movie] {
        switch movieCategoryType {
        default:
            return [Movie]()
        }
    }
}
